# Generated by patternizer
# This Makefile includes the common pattern targets from Makefile-common
# You can add custom targets above or below the include line

##@ Platform Setup Tasks
.PHONY: create-rosa-cluster
create-rosa-cluster: ## Provision a ROSA Classic cluster (HA with GPU by default)
	@bash scripts/create-rosa-cluster.sh $(ROSA_ARGS)

.PHONY: configure-cluster
configure-cluster: ## Configure cluster infrastructure (ODF/NooBaa, MachineSet scaling)
	@echo "Configuring cluster infrastructure..."
	@bash scripts/configure-cluster-infrastructure.sh

.PHONY: show-cluster-info
show-cluster-info: ## Show cluster topology, version, and platform info
	@bash scripts/detect-cluster-topology.sh 2>/dev/null || true
	@echo ""
	@oc version 2>/dev/null | head -2 || true

.PHONY: check-prerequisites
check-prerequisites: ## Validate cluster prerequisites for deployment
	@bash scripts/configure-cluster-infrastructure.sh --dry-run

##@ Distribution Tasks
.PHONY: sync-operator-chart
sync-operator-chart: ## Sync charts/hub/ to kubeheal-operator repo
	@bash scripts/sync-operator-chart.sh $(SYNC_ARGS)

include Makefile-common
